version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_raise_db
    restart: always
    environment:
      POSTGRES_USER: root # user mặc định
      POSTGRES_PASSWORD: passed # password mặc định
      POSTGRES_DB: raise # tên database mặc định khi start
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: doanngocnam3002@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passed
    ports:
      - '8888:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
